### ISSUE TITLE
Sample Files

### ISSUE THREAD

**Issue by Yida-Lin** [cbrnr/mnelab#10]
@cbrnr Clemens! :)

Do you have a few sample `.bdf` / `.edf` files for me to play around with?

**Comment by cbrnr** [comment]
Sure, I've uploaded a couple to our shared folder on Google Drive.

**Comment by brylie** [comment]
The [Swartz Center for Computational Neuroscience](https://sccn.ucsd.edu/) has a [list of free EEG data](https://sccn.ucsd.edu/~arno/fam2data/publicly_available_EEG_data.html).
