### ISSUE TITLE
MNELAB closes when trying to open .gdf files. 

### ISSUE THREAD

**Issue by melyndaschreiber** [cbrnr/mnelab#106]
Hello all, 
Can MNELAB open .gdf files? Are there certain files that it cannot open? I tries to open a dataset and it close the program instead of giving me an error that said it cannot open the file. Any help on this is appreciated. 
Thanks.

**Comment by cbrnr** [comment]
MNELAB should be able to open all formats supported by MNE (which includes GDF). In addition, MNELAB supports loading XDF. Can you send me the file so I can take a look what the problem is?

**Comment by cbrnr** [comment]
@melyndaschreiber any chance you could send me the problematic GDF file so that I can fix the problem?

**Comment by cbrnr** [comment]
Closing due to no response. Feel free to open a new issue if you encounter this problem with a specific GDF file again.
