### ISSUE TITLE
Add PyPI CI checks

### ISSUE THREAD

**Issue by cbrnr** [cbrnr/mnelab#124]
We should have a CI job which automatically checks PyPI package build.

**Comment by stralu** [comment]
For PEP checks, we could use the github integration [pep8speaks](https://github.com/OrkoHunter/pep8speaks). It runs a PEP8 checker (pycodestyle/flake8) on all python lines after a pull request is created and updates the status after each commit.

**Comment by cbrnr** [comment]
Yes. Or we could run `flake8` in one of our already existing Azure Pipelines jobs.

Or we could try a GitHub action such as https://github.com/marketplace/actions/pycodestyle.

**Comment by gdolle** [comment]
Related to #186. 

Also maybe flake8 could be integrated too (see https://flake8.pycqa.org/en/2.5.5/setuptools.html)

**Comment by cbrnr** [comment]
Yes, we're already using flake8. Now only a packaging test needs to be added.

**Comment by cbrnr** [comment]
We now build wheels on every PR and release.
