### ISSUE TITLE
Each data set should have a unique ID

### ISSUE THREAD

**Issue by cbrnr** [cbrnr/mnelab#127]
A unique ID for each data set is necessary, otherwise we can't distinguish them (by name is not necessarily unique, nor is by position in the list of open data sets). I suggest that each data set gets an integer ID starting at 0.

**Comment by cbrnr** [comment]
It will probably be necessary to switch `model.data` from a list to a dict with the unique IDs as keys.

**Comment by cbrnr** [comment]
On second thought, because the data sets need to be ordered (reflected in the left sidebar), a list is probably still required.

**Comment by hoechenberger** [comment]
> On second thought, because the data sets need to be ordered (reflected in the left sidebar), a list is probably still required.

Since Python 3.6, dictionaries preserve insertion order, so one _could_ use dicts. Also why not use a hash value calculated from the dataset as ID?

**Comment by cbrnr** [comment]
> Since Python 3.6, dictionaries preserve insertion order, so one could use dicts.

Yes, you're right, dict could be an option, but I think a list is probably a better option for this use case. We don't care for access time (lists are much slower), because there will only be a few open data sets. We do care for the order, because that's how the list is visualized in the sidebar.

> Also why not use a hash value calculated from the dataset as ID?

Hm, hashing might work but this requires careful thinking. For example, I can load the exact same data set twice (or more) - each copy should have a different ID. Also, I'm not sure if datasets are hashable because they are mutable (if you meant hashing e.g. a `Raw` object). Therefore, the easiest thing to do should be to use a counter and increment it every time a new data set is created.

I just tried this out and found that a `Raw` object is mutable and hashable, but this should never happen in Python:

```python
>>> import mne
>>> raw = mne.io.read_raw_edf("some_test.edf", preload=True)
>>> id(raw)
4939779712
>>> hash(raw)
104378563032721740
>>> raw.crop(0, 10)
...
>>> id(raw)
4939779712
>>> hash(raw)
871140848923410585
```

🙀 -  I thought that an object is hashable if it has a hash value that **never** changes during its lifetime (https://docs.python.org/3/glossary.html#term-hashable)?

**Comment by cbrnr** [comment]
I think we're good here. It's actually OK that a `Raw` object is hashable and mutable. Since the hash is used for comparison, it makes sense that it changes when manipulating the object.

Regarding this issue, I think we could maybe use the hash of the data object, but what if something else changes (e.g. an attribute that isn't contained in the `Raw` object such as the name)?

**Comment by cbrnr** [comment]
I think it is not necessary to change anything with the current data model. We track all changes to the list, so we should be fine.
