### ISSUE TITLE
Replace pebble with standard library modules

### ISSUE THREAD

**Issue by cbrnr** [cbrnr/mnelab#138]
Currently we require `pebble` because `multiprocessing.Pool` did not work with the workaround introduced for Anaconda on macOS (#119). In theory, it should be possible to make do without `pebble`, because this package is just a wrapper for some standard library modules.

**Comment by hoechenberger** [comment]
You may assign me, but I cannot promise any action within the next two weeks as I’m relocating  :)

**Comment by cbrnr** [comment]
Thanks @hoechenberger, no worries, this is not urgent. You are now officially working on MNE, right? Have a safe trip and a good start!

**Comment by hoechenberger** [comment]
Yes, will be working with Alex Gramfort starting Monday! Thank you :)

**Comment by cbrnr** [comment]
I think it might be worth trying to figure out why the MWE you posted doesn't work with Anaconda's `pythonw`:

```python
import multiprocessing
import time


def f():
    print('Executing f()...')


if __name__ == '__main__':
    pool = multiprocessing.Pool()
    pool.apply_async(func=f)

    time.sleep(1)

    pool.terminate()
    pool.join()
```

**Comment by cbrnr** [comment]
I think the problem might really be the different `python` versions in `anaconda/bin` and `anaconda/python.app/Contents/MacOS`. Indeed, I removed `anaconda/python.app/Contents/MacOS` and replaced it with a symbolic link to the normal `anaconda/bin/python` - and everything works! 😱 😮

**Comment by hoechenberger** [comment]
Wow this is crazy! But it still doesn't answer the question why it would work via `pebble`!

**Comment by cbrnr** [comment]
Well yes, but IMO this is not the main question now that we know that it works. Maybe `pebble` does something clever to always start the original `python` process. I think I'll open an issue to let Anaconda know that the versions need to be the same.

**Comment by hoechenberger** [comment]
Believe it or not, but it's working with Anaconda's and `conda-forge`'s latest `pythonw` (3.8.0). Still failing with 3.7.

```
➜  /tmp pythonw --version
Python 3.8.0
➜  /tmp python --version
Python 3.8.1
```

**Comment by cbrnr** [comment]
Even though the versions don't match exactly? I'd still say this would be nice to have.

**Comment by hoechenberger** [comment]
Yes to both.

**Comment by cbrnr** [comment]
Reported in https://github.com/ContinuumIO/anaconda-issues/issues/11633.
