### ISSUE TITLE
Errors in running mnelab.py

### ISSUE THREAD

**Issue by aung2phyowai** [cbrnr/mnelab#14]
I cloned the mnelab directly from github.  I installed mne and other packages through Anaconda under 'mne' environment. When I run mnelab.py as intructed, I faced the following error. Any quick fix? 

(mne) F:\GitHub-Projects\mnelab\mnelab>python mnelab.py
Traceback (most recent call last):
  File "mnelab.py", line 16, in <module>
    from .dialogs.filterdialog import FilterDialog
ModuleNotFoundError: No module named '__main__.dialogs'; '__main__' is not a package

**Comment by cbrnr** [comment]
I've restructured the project recently. In your environment, change into the root of the project directory (presumably `F:\GitHub-Projects\mnelab` in your case) and start MNELAB like this:

    python main.py

**Comment by cbrnr** [comment]
Actually, this issue reminded me that I used really bad names. I've renamed `main.py` to `mnelab.py` so that you can now start MNELAB with:

    python mnelab.py
