### ISSUE TITLE
How to start

### ISSUE THREAD

**Issue by zeos** [cbrnr/mnelab#143]
Hi! 

Thank you for developing mnelab.
 
I am running on Windows 10x64 Pro with Python 3.8.2 installed.
When I start MNELAB, and the program opens, everything is disabled except the [Open] & [Quit] buttons. Is there a tutorial how-to start? I am using Muse 2016 and have .muse files, and exported CSV data using muse-player. How can I import the data or what kind of RAW data is supported?

Thank you for your time! Any pointers and help are appreciated. 

kind regards

**Comment by cbrnr** [comment]
You are actually addressing a very important point (probably the most important one at the moment). Currently, I don't have any documentation - this is something I need to add very soon. I'll probably start with a short tutorial on my website at cbrnr.github.io. I'll leave this issue open to remind myself to do it. Also, I'll post a message here once the tutorial is available.

Regarding your specific questions, I have never worked with Muse CSV files. MNELAB supports all files supported by MNE (a non-exhaustive list is available at https://mne.tools/stable/auto_tutorials/io/plot_20_reading_eeg_data.html) plus XDF (https://github.com/xdf-modules/xdf-python). It might be possible to extract code from https://github.com/arunrawlani/museplayer to implement a .muse reader in MNE, but currently I don't have the time to do it.

If you have converted the data to CSV, it should be pretty straightforward to read it with MNE, but MNELAB currently has no dialog/option to load custom CSV files. This might be a nice addition, so feel free to open another issue describing the specific Muse CSV format and what might be necessary to implement something more generic in MNELAB.

**Comment by zeos** [comment]
Thank you for your reply!

I am currently using realtime_mne with LSL client. 

However, I want to conduct offline additional analysis on the data I have collected, with MNELAB. 

Still I am puzzled how to use the MNELAB? What is the typical workflow? Is it normal that everything is grayed-out (disabled)? Can you upload a test.csv and few lines of text how to start?

Thank you for your work and your time!

**Comment by cbrnr** [comment]
MNELAB is currently in a very early state. Also, MNELAB "just" provides a GUI for MNE-Python, which is why I'd currently recommend that you analyze your data with MNE-Python directly.

Regarding the workflow, yes, it is normal that almost everything is grayed out if there is no open file. Once you open a file, menu items will be activated depending on which actions are supported with the open data set. If you want to try it out, you could start with an example .edf file (e.g. the file used in [this blog post](https://cbrnr.github.io/2017/10/23/loading-eeg-data/)).

**Comment by cbrnr** [comment]
We have now added documentation at [mnelab.readthedocs.org](https://mnelab.readthedocs.io/en/latest/).
