### ISSUE TITLE
Features

### ISSUE THREAD

**Issue by tayyabafaisal** [cbrnr/mnelab#150]
Hi @cbrnr 
Can you please direct me to appropriate function to extract feature from edf file in MNE.Need to extract features for localisation of abnormalities in signal

**Comment by cbrnr** [comment]
What do you mean by feature? What would you like to do with the EDF file?

**Comment by tayyabafaisal** [comment]
I would like to localise abnormalities in EEG signal

**Comment by tayyabafaisal** [comment]
can I get your email if its not related to your repository

**Comment by cbrnr** [comment]
Please use the mailing list (https://mail.nmr.mgh.harvard.edu/mailman/listinfo/mne_analysis) or the Gitter channel (https://gitter.im/mne-tools/mne-python?source=orgpage) to ask your question. It would be helpful if you could be more specific in what you would like to achieve, how you would like to achieve it, and what you have already tried.
