### ISSUE TITLE
Adapt icons to dark mode

### ISSUE THREAD

**Issue by cbrnr** [cbrnr/mnelab#151]
Currently MNELAB icons look good only in light mode (text works in both modes because it adapts). In dark mode, icons should be inverted. I don't know if Qt supports automatic dark/light mode settings though.

<img width="941" alt="Screen Shot 2020-06-01 at 15 04 14" src="https://user-images.githubusercontent.com/4377312/83411800-3f381880-a419-11ea-8f9b-ff9fcd8813b0.png">

**Comment by GuillaumeFavelier** [comment]
What a beautiful dark theme! I would love to see the result with white/lighter icons indeed.

After a quick search I got this (source a bit old): 
https://forum.qt.io/topic/77212/how-to-change-qpushbutton-icon-color

But I could not find any mention to `QVariantMap` so I could not try it.

---

I also found a [solution with `QPainter`](https://stackoverflow.com/questions/24943711/qt-drawing-icons-using-color-and-alpha-map) on stackoverflow:

```py
color = QColor(255, 0, 0)  # red for example
pixmap = QPixmap("mask.png")
painter = QPainter(pixmap)
painter.setCompositionMode(QPainter.CompositionMode_SourceIn)
painter.fillRect(pixmap.rect(), color)
painter.end()
icon = QIcon(pixmap)
```

This looks very flexible but the main drawback in my opinion is that by using `QPixmap` you don't use `SVG` anymore.

---

There is also the backup plan with 2 sets of icons to change dynamically according to the style.

**Comment by cbrnr** [comment]
Thanks @GuillaumeFavelier, I'll check these links out {I kind of would like to keep the SVGs though). I think having two sets of icons isn't a bad solution at all - but how would I detect which OS theme is currently active? Currently, what you see in the screenshot happens automatically if macOS is in dark mode, no manual intervention required.

**Comment by GuillaumeFavelier** [comment]
> no manual intervention required

This is neat!

Following https://forum.qt.io/topic/99799/qt-5-12-1-and-dark-mode-on-macos-mojave-10-14/8 and https://github.com/spyder-ide/spyder/issues/10026 it seems to be tricky to detect.

You could try with [`changeEvent()`](https://github.com/spyder-ide/spyder/issues/10026#issuecomment-521969833). I don't have macOS so I don't know how reliable this is.

**Comment by cbrnr** [comment]
I hope this can be detected more reliably now as compared to when this issue was reported. If so, all we need to do is load a different set of icons. I'll try and see how this goes. Also, this should in theory also work on Windows 10 and Linux (at least GNOME), both of which support system-wide light and dark themes.

**Comment by cbrnr** [comment]
Yep, at least on macOS I can catch `QEvent.PaletteChange` every time the system theme changes. Now the only question remaining is how do I detect which theme (light or dark) is active initially?

**Comment by cbrnr** [comment]
@GuillaumeFavelier see #152.

**Comment by burhanaksendir** [comment]
> Currently MNELAB icons look good only in light mode (text works in both modes because it adapts). In dark mode, icons should be inverted. I don't know if Qt supports automatic dark/light mode settings though.
> 
> <img alt="Screen Shot 2020-06-01 at 15 04 14" width="941" src="https://user-images.githubusercontent.com/4377312/83411800-3f381880-a419-11ea-8f9b-ff9fcd8813b0.png">

Hi,
I have prepared an example for this. You can view it at the address below.
https://gist.github.com/burhanaksendir/f82ddfa9372edc5e7923b3ddb6b9e32f

**Comment by cbrnr** [comment]
Thanks @burhanaksendir, that's really useful! That way there needs to be only one icon set.

**Comment by burhanaksendir** [comment]
> Thanks @burhanaksendir, that's really useful! That way there needs to be only one icon set.

You are welcome.
