### ISSUE TITLE
mnelab command on Windows doesn't work

### ISSUE THREAD

**Issue by cbrnr** [cbrnr/mnelab#153]
Installing `mnelab` from conda-forge requires a hefty 2.7GB of packages (I think because it installs all required and optional dependencies for MNE).

Therefore, I thought that when using `conda` an alternative could be:

```
$ conda install numpy scipy matplotlib qtpy pyqt
$ pip install mne --no-deps
$ pip install mnelab --no-deps
```

This is much lighter and it works, but starting MNELAB only works with `python -m mnelab`. The `mnelab` command displays the following error message:

<img width="163" alt="mnelab_start_windows" src="https://user-images.githubusercontent.com/4377312/83730401-50676c00-a649-11ea-9afa-de2d5260bbd2.png">

It might have something to do with the modified `__main__.py`, where we integrated a workaround for conda on macOS to get a functional GUI (using `pythonw`). @hoechenberger do you have any ideas?

**Comment by hoechenberger** [comment]
> Installing `mnelab` from conda-forge requires a hefty 2.7GB of packages (I think because it installs all required and optional dependencies for MNE).

On `conda-forge` they ~recently started a transition from `matplotlib`, which included PyQt as a dependency, to `matplotlib-base` for cases where you "just" need to plot, but don't require any GUI to interact with the created figure.

I propose we do something similar for MNE.

We could have `mne-base`, which would install everything you need to have for sensor-level analysis incl. interactive plotting; and `mne`, which additionally installs VTK etc.

Thoughts?
cc @larsoner

**Comment by cbrnr** [comment]
This is not even the main issue I wanted to discuss here 😄 - but here goes. MNELAB requires PyQt5 (or PySide2) anyway, so removing that doesn't really work. But I know, this was not your point. I like the idea of having an `mne-base` package. This means that `mne` would depend on `mne-base` and include other additional things, right?

Could we maybe discuss this in a separate issue (maybe at the conda-forge recipe)?

Here I'd like to talk about the issue why starting MNELAB doesn't work.

**Comment by hoechenberger** [comment]
> This is not even the main issue I wanted to discuss here

I know, lazy me was just hoping to avoid it haha :D I would have to look into this… won't be able to do it today, probably Saturday or so? :)

**Comment by cbrnr** [comment]
@hoechenberger I still have this problem - it looks like `mnelab` is actually an `.exe` file in `$ANACONDA/Scripts`. Do you have any idea how I could debug this? The `mne` command (also an `.exe`) does work...

**Comment by hoechenberger** [comment]
Can you ping me again in a few days? Currently busy with something else but definitely interested in tracking this down!

**Comment by cbrnr** [comment]
Quick update, the problem persists on `main` when doing `pip install .`. However, if I do `pip install -e .` starting using the `mnelab` command works. Strange.

**Comment by cbrnr** [comment]
Question on SO: https://stackoverflow.com/questions/66137439/python-gui-entry-point-not-working-on-windows

**Comment by cbrnr** [comment]
It does work if I use the `console_scripts` entry point in `setup.py` though. However, this requires the console window to remain open while MNELAB is running, which is not ideal.

**Comment by larsoner** [comment]
Did you try the [gui_scripts](https://packaging.python.org/specifications/entry-points/#use-for-scripts) entrypoint?

**Comment by hoechenberger** [comment]
> Did you try the [gui_scripts](https://packaging.python.org/specifications/entry-points/#use-for-scripts) entrypoint?

That's what we used before
