### ISSUE TITLE
Plotting windos don't have status bar to hide anymore

### ISSUE THREAD

**Issue by abcsds** [cbrnr/mnelab#161]
When plotting data it's not necessary to hide the status bar. When trying to do so mnelab crashes with the following error:
```
AttributeError: 'NoneType' object has no attribute 'hide'
```

**Comment by cbrnr** [comment]
Thanks, I have also noticed this change. Do you know if this is caused by an update to Matplotlib or PyQt5 (and which version introduced that change)?

**Comment by cbrnr** [comment]
It seems to be a Matplotlib change: https://matplotlib.org/3.3.1/api/api_changes.html#statusbar-classes-and-attributes
