### ISSUE TITLE
ICA hangs (at least on macOS)

### ISSUE THREAD

**Issue by cbrnr** [cbrnr/mnelab#165]
When running ICA, MNELAB hangs after the computation finishes. The "Calculating" dialog window stays open even though the ICA has clearly finished (according to the message in the terminal window). I'm not sure when this stopped working and if this also affects Windows and Linux, so more testing is needed.

**Comment by abcsds** [comment]
The three methods are working on Linux. Could it be an OS-related issue?

**Comment by cbrnr** [comment]
This is still a thing on macOS BIg Sur unfortunately.
