### ISSUE TITLE
Related projects

### ISSUE THREAD

**Issue by mmagnuski** [cbrnr/mnelab#17]
I just wanted to point out two related projects that mnelab might benefit from:
* [eeg-timeFreqToolbox](https://github.com/fcbg-hnp/eeg-timeFreqToolbox) - seems to be a GUI for multiple time-frequency options that are in mne
* [eeg-ICAtoolbox](https://github.com/fcbg-hnp/eeg-ICAtoolbox) - judging from the name - some GUI tools for ICA.  

I didn't investigate any of these projects beyond what is shown on the main github page, but thought it might be useful to notify you.

**Comment by cbrnr** [comment]
Thanks for the heads up. These are specialized dialog windows for very specific purposes. I think it'll be useful to let the author know that we're developing MNELAB.
