### ISSUE TITLE
Bug with export function call and args number

### ISSUE THREAD

**Issue by gdolle** [cbrnr/mnelab#176]
Hi,

There's a problem with this line that makes export crash
https://github.com/cbrnr/mnelab/blob/master/mnelab/mainwindow.py#L447

It assumes that all filter functions have the same number of arguments which is not the case, for instance

https://github.com/cbrnr/mnelab/blob/master/mnelab/model.py#L162
https://github.com/cbrnr/mnelab/blob/master/mnelab/model.py#L178

I'll propose a PR (@cbrnr ;) )

**Comment by cbrnr** [comment]
Fixed by #177.
