### ISSUE TITLE
Load 2D arrays from .mat and .npy

### ISSUE THREAD

**Issue by jgcaffari1** [cbrnr/mnelab#195]
It would be useful to be able to load ieeg/eeg recordings saved as numpy arrays.  

Is anyone working on this?

**Comment by cbrnr** [comment]
In principle this would be no problem at all, but .npy files can contain arbitrary NumPy arrays. Is there any particular format/device that specifies the structure contained in such a file? Do you have an example file that you could share?

**Comment by jgcaffari1** [comment]
I was thinking about giving it an array with dimensions [channels, time points], converting it to a RawArray, then plotting it with row numbers as lead names.

**Comment by cbrnr** [comment]
I think it would still be useful to have an option to load 2D array data, which could be stored as .npy or probably even more popular .mat. Missing meta-information such as fs could be queried in a dialog.
