### ISSUE TITLE
Test PySide6 and PyQt6

### ISSUE THREAD

**Issue by cbrnr** [cbrnr/mnelab#198]
If these latests versions work (hopefully also with QtPy), we should make them our default recommendations (in `README.md` etc). Once Matplotlib support is out, it might also be worth considering supporting only PySide6 in the future for the following reasons:

- PySide6 is the officially supported Qt bindings package for Python, which has received continuous updates
- PySide6 provides binary wheels on PyPI for Windows, macOS (no ARM64 at the moment though), and Linux
- PySide6 is licensed under the LGPL, which is potentially less problematic when used with BSD- or MIT-licensed code (PyQt5 is GPL or commercial only)

Potential blockers (in descending severity):
- ~~Matplotlib support is required (https://github.com/matplotlib/matplotlib/pull/19255)~~
- Anaconda/Conda-Forge packages might not be available for a long time (they are still stuck at Qt 5.12 from end of 2018 because upgrading to even 5.15 seems to be problematic)
- macOS ARM64 wheels are currently not available

**Comment by GuillaumeFavelier** [comment]
About `QtPy` there are some open issues on this topic:

https://github.com/spyder-ide/qtpy/issues/233
https://github.com/spyder-ide/qtpy/issues/229

**Comment by cbrnr** [comment]
Thanks @GuillaumeFavelier. Let's hope that the devs react, I have the impression that the project is currently unmaintained.

**Comment by GuillaumeFavelier** [comment]
They could be waiting for further versions like `6.1` or `6.2`? I don't know.

> Let's hope that the devs react

:100:

**Comment by cbrnr** [comment]
Also, since MNELAB depends on Matplotlib we need to wait for https://github.com/matplotlib/matplotlib/pull/19255 to get merged upstream.

**Comment by congzhangzh** [comment]
@cbrnr maybe, you can give https://github.com/medlab/matplotlibqml a try, which focuses on PySide6 and latest Qt

**Comment by cbrnr** [comment]
Thanks for the heads up!

**Comment by cbrnr** [comment]
PySide6 works now, implemented in #237.
