### ISSUE TITLE
How to save edited data?

### ISSUE THREAD

**Issue by iampalop** [cbrnr/mnelab#229]
I removed some events on raw data from .bdf file and then export to .fif file, but the new .fif file is the same as .bdf file that hasn't been removed from any event.

**Comment by cbrnr** [comment]
Currently, it is not possible to export events together with the data file. There are two options:

1. Export the events to a separate file using "File" – "Export events..." (which can be imported again with "File" – "Import events...").
2. Convert events to annotations and export to e.g. FIF. In contrast to events, annotations are stored with the file. You can always convert annotations to events should you need them ("Tools" – "Create events from annotations").
