### ISSUE TITLE
Missing font warning in History dialog

### ISSUE THREAD

**Issue by cbrnr** [cbrnr/mnelab#254]
When opening _View_ – _History..._, the following warning pops up in the terminal:

```
qt.qpa.fonts: Populating font family aliases took 520 ms. Replace uses of missing font family "Monospace" with one that exists to avoid this cost.
```

I think it would be good to fix this because half a second is noticeable.

**Comment by cbrnr** [comment]
@GuillaumeFavelier have you ever seen such a warning? Do you know how this could be resolved?

**Comment by GuillaumeFavelier** [comment]
I never saw this error before but could it be related to this thread in the Qt forum?

https://forum.qt.io/topic/119302/missing-font-family-warning-on-macos/13

With a bit more research, I also found 2 bug reports though:

One closed: https://bugreports.qt.io/browse/QTBUG-87267 (this one affects `Qt 5.15.1`)
And one still open: https://bugreports.qt.io/browse/QTBUG-101310 (this one affects `Qt 6.2.3`)

**Comment by GuillaumeFavelier** [comment]
It is old but it might be worth trying these changes as well:

https://github.com/dolphin-emu/dolphin/pull/9085/files

**Comment by cbrnr** [comment]
Thanks @GuillaumeFavelier, I will try if any of these solutions work. Indeed, I don't have a font called "Monospace" on my Mac (which I initially thought to be the case). So this at least explains the error message, because of course it cannot find the font if it's not available.

**Comment by cbrnr** [comment]
These solutions don't work on my Mac, because I get a strange value for the default monospace system font (`.AppleSystemUIFontMonospaced`) which doesn't exist. Therefore, I'm now selecting monospace fonts by platform (which are known to exist). @GuillaumeFavelier maybe you could test this on Linux to see if (1) the font looks good and (2) the warning message disappeared.

**Comment by GuillaumeFavelier** [comment]
I'll try #337 shortly and report back :+1:
