### ISSUE TITLE
Icons not showing on Linux

### ISSUE THREAD

**Issue by cbrnr** [cbrnr/mnelab#292]
Icons are not showing on Linux. To reproduce, simply `pip install mnelab` and then run `mnelab` or `python -m mnelab` on Linux. The main window looks like this:
![Screenshot from 2022-02-14 11-41-09](https://user-images.githubusercontent.com/4377312/153848997-e9ce308e-9aa2-460e-a086-6e8f5fe94f87.png)
@hofaflo can you reproduce this on Linux (to rule out that it's just me)?

**Comment by hofaflo** [comment]
Sorry, I can't even get it to run in WSL 😬

**Comment by cbrnr** [comment]
😢 - why is is not working on WSL? What error do you get? But I guess this is a separate topic...

**Comment by cbrnr** [comment]
@larsoner you're using Linux - do you get icons when running the latest (pip installed) MNELAB v0.7.0?

**Comment by larsoner** [comment]
```
larsoner@bunk:~$ pip install mnelab
Collecting mnelab
  Downloading mnelab-0.7.0-py3-none-any.whl (71 kB)
     |████████████████████████████████| 71 kB 2.6 MB/s            
Collecting PySide6>=6.2.0
  Downloading PySide6-6.2.3-6.2.3-cp36.cp37.cp38.cp39.cp310-abi3-manylinux1_x86_64.whl (269.3 MB)
     |████████████████████████████████| 269.3 MB 25 kB/s               
Collecting pyxdf>=1.16.0
  Using cached pyxdf-1.16.3-py2.py3-none-any.whl (15 kB)
...
Collecting shiboken6==6.2.3
  Downloading shiboken6-6.2.3-6.2.3-cp36.cp37.cp38.cp39.cp310-abi3-manylinux1_x86_64.whl (1.0 MB)
     |████████████████████████████████| 1.0 MB 153.8 MB/s            
...
Successfully installed PySide6-6.2.3 mnelab-0.7.0 pyxdf-1.16.3 shiboken6-6.2.3
larsoner@bunk:~$ mnelab
...
  File "/home/larsoner/.local/lib/python3.10/site-packages/mnelab/viz.py", line 9, in <module>
    from mne.viz.utils import center_cmap
ImportError: cannot import name 'center_cmap' from 'mne.viz.utils' (/home/larsoner/python/mne-python/mne/viz/utils.py)
```
Downgrading to 0.24 I get:

![Screenshot from 2022-02-14 13-04-40](https://user-images.githubusercontent.com/2365790/153921003-49c1bd99-4b46-4628-9998-26f35a50380e.png)

**Comment by cbrnr** [comment]
Thanks @larsoner! Good to know that it's probably just my Arch Linux (although that doesn't really make it any easier to debug).

The import error is unrelated, but something we need to fix ASAP!

**Comment by cbrnr** [comment]
The package `qt6-svg` needs to be installed on Arch Linux, this is only an optional dependency of `pyside6`.
