### ISSUE TITLE
Name collision

### ISSUE THREAD

**Issue by hoechenberger** [cbrnr/mnelab#31]
It seems the name `mnelab` has recently been adopted by another project, too: https://github.com/mohirio/mnelab

@cbrnr‘s mnelab went public first, though…

**Comment by cbrnr** [comment]
Thanks for pointing this out. It would be nice if this could be resolved in order to avoid confusion.

**Comment by mohirio** [comment]
Hi, thank for the notice and sorry for delayed reply.

I wasn't aware of this project and I don't mind changing the name, however I want to point out that my project is just a Docker image and not a Python package, so there shouldn't be any confusion really when installing through ```pip``` or ```conda```.

**Comment by cbrnr** [comment]
It would be awesome if you could come up with a different name. Even though there should be no confusion with the corresponding package install mechanisms, I think people might still be confused by two projects related to MNE having the exact same name.

**Comment by mohirio** [comment]
Done! The project name is now changed to [mne-jupyterlab](https://github.com/mohirio/mne-jupyterlab).

**Comment by cbrnr** [comment]
Cool, thanks!
