### ISSUE TITLE
Use infowidget when no file is open

### ISSUE THREAD

**Issue by cbrnr** [cbrnr/mnelab#312]
I think we could use the infowidget to display information like which file formats can be opened, shortcuts, etc. instead of just an empty gray area when no dataset is open. Inspired by VS Code, which I really like:
<img width="930" alt="Screen Shot 2022-02-19 at 11 56 51" src="https://user-images.githubusercontent.com/4377312/154798075-37675eab-4376-4444-b9aa-16e368c619b2.png">

**Comment by GuillaumeFavelier** [comment]
Do you also consider the toolbar on the left? :grin:

**Comment by cbrnr** [comment]
No, here I just meant the white empty editor space 😄!
