### ISSUE TITLE
PySide6 github-action

### ISSUE THREAD

**Issue by dridk** [cbrnr/mnelab#327]
you should share your PySide6-Linux github-action from the marketplace. It was really usefull 
https://github.com/marketplace?type=actions

**Comment by cbrnr** [comment]
Do you mean this part?

```
    - name: Install Linux packages
      run: |
        sudo apt update
        sudo apt install libxcb-icccm4 libxcb-image0 libxcb-keysyms1 \
                         libxkbcommon-x11-0 xvfb libxcb-randr0 \
                         libxcb-render-util0 libxcb-xinerama0 libegl1
```

Or anything in addition? Yes, it might make sense to outsource this to an action...

**Comment by dridk** [comment]
I can do it if you accept .

**Comment by cbrnr** [comment]
Of course, that would be great! This should be useful for Qt6 in general, not just PySide6, right?

**Comment by dridk** [comment]
yes, for all version of Qt/python. Or maybe one action per framework.

**Comment by cbrnr** [comment]
Sounds good! I'd make just one action for Qt on a Linux image and mention that it should be used for PySide6/PyQt6 in addition to plain Qt6.

**Comment by cbrnr** [comment]
I'm closing this because there's nothing more to discuss I think. It would be great if you posted a link to the action here once you've created it.
