### ISSUE TITLE
EEG MNE data crop issue

### ISSUE THREAD

**Issue by Deepucdactvm** [cbrnr/mnelab#361]
hey i have mne plot eeg data, my events lies between two eye blinks, i want to crop that event portion only is it possible?``

**Comment by cbrnr** [comment]
What exactly do you want to do? Currently, it is only possible to crop data by specifying start and end time points. Is this not sufficient?

**Comment by cbrnr** [comment]
This seems like a general usage question, please ask your question on the [MNE Discourse](https://mne.discourse.group/). If this is an MNELAB issue, please feel free to reopen and provide more details.
