### ISSUE TITLE
MNELAB on windows11 does not work

### ISSUE THREAD

**Issue by allwaysFindFood** [cbrnr/mnelab#366]
Hi~I need help.
I installed mnelab on windows 11, started MNELAB in a terminal with mnelab, but nothing happend. No error message, no window.
code like this:
```
pip install mnelab 
pip install mnelab[full]  (uninstalled above)
pip install git+https://github.com/cbrnr/mnelab  (uninstalled above)
```

I usd  `conda install mnelab`, and started MNELAB in a terminal with mnelab, No windows, but showed some message:
```
Traceback (most recent call last):
  File "C:\Users\anaconda3\envs\mne_mne\Scripts\mnelab-script.py", line 6, in <module>
    from mnelab.__main__ import main
  File "C:\Users\anaconda3\envs\mne_mne\lib\site-packages\mnelab\__init__.py", line 11, in <module>
    from .mainwindow import MainWindow
  File "C:\Users\anaconda3\envs\mne_mne\lib\site-packages\mnelab\mainwindow.py", line 30, in <module>
    from .viz import plot_erds
  File "C:\Users\anaconda3\envs\mne_mne\lib\site-packages\mnelab\viz.py", line 8, in <module>
    from mne.viz.utils import center_cmap
ImportError: cannot import name 'center_cmap' from 'mne.viz.utils' (C:\Users\anaconda3\envs\mne_mne\lib\site-packages\mne\viz\utils.py)
```
Think you!

**Comment by cbrnr** [comment]
Can you please post the errors you get when installing via `pip`? The `conda` package is outdated and not officially supported. The error should be a different one, because what you posted shows code from an old version of MNELAB which does not exist anymore.

**Comment by allwaysFindFood** [comment]
I use conda create .... 
Python  version is 3.9.15

**Comment by cbrnr** [comment]
I don't think MNELAB is working with conda (yet), because PySide6 is still not available. Mixing conda and pip is always asking for trouble, so could you please try to install Python from the [official installers](https://www.python.org/downloads/) and then try again with `pip install mnelab`?

**Comment by cbrnr** [comment]
I just tried it on Windows 11 and it worked for me. Can you try starting MNELAB as follows:

```
python -m mnelab
```

You should then see a detailed error message. I suspect that you might have an old Matplotlib version. You need >= 3.6.2, versions 3.6.0 and 3.6.1 do *not* work.

**Comment by allwaysFindFood** [comment]
I installed Python 3.10 from the official installers not using conda and then try with` pip install mnelab`. It's worked !
I tryed with ` python -m mnelab ` on a conda env, It's also worked!
Thank you !

**Comment by cbrnr** [comment]
Nice, you're welcome!
