### ISSUE TITLE
open mnelab with a preloaded file 

### ISSUE THREAD

**Issue by guiomar** [cbrnr/mnelab#388]
Hi @cbrnr! 

Is it possible to open mnelab with a preloaded file calling it from commanline?

**Comment by cbrnr** [comment]
Yes, you can pass the filename as an argument, e.g. `mnelab test.edf`. We should really add a command line parser so that at least `mnelab --help` works though...

**Comment by guiomar** [comment]
That's wonderful! thanks for your super fast response!

**Comment by guiomar** [comment]
That's wonderful! thanks for your super fast response!
