### ISSUE TITLE
Apply ICA

### ISSUE THREAD

**Issue by vferat** [cbrnr/mnelab#40]
As mentioned in #34, and way to use ica.apply() would be a nice feature.

**Comment by vferat** [comment]
Which name extension would we want to add to the dataset name  when applying ica ?

Maybe the ICA method or just ICA ?
* current name  +  method : mydataset-INFOMAX
* current name  +  ICA : mydataset-ICA

**Comment by cbrnr** [comment]
I'd prefer just ICA - information on which algorithm was used should be available in the info structure. I'm currently putting this in parentheses after the data set name, e.g. "mydataset" -> "mydataset (ICA)".
