### ISSUE TITLE
Better defaults with raw plot

### ISSUE THREAD

**Issue by danieltomasz** [cbrnr/mnelab#407]
The PR https://github.com/cbrnr/mnelab/pull/403 seems to fix the problem with  `canvas` and `raw_plot`,
 but since it is using under hood mne.viz.set_browser_backend('qt'), it would be great to  have similar defaults as  mne.viz.plot_raw(raw),

 currently mnelab` is trying to show all channels with some non-default scaling, so with long HD-EEG it make it very hard to see what showing with eeg

Results from `_ = mne.viz.plot_raw(raw)`
![image](https://github.com/cbrnr/mnelab/assets/7980381/e69e0d9d-a47c-4f07-b990-97f2a8b690ab)

Below `mnelab`
by default it is using `data.plot(events=events, n_channels=258)`
<img width="1286" alt="image" src="https://github.com/cbrnr/mnelab/assets/7980381/b4218e3b-59dc-4f8d-9a57-aa873341e947">

**Comment by cbrnr** [comment]
Should we use a default of 20 channels as well? Maybe it would be nice to customize the default settings (like number of channels and time segment per page) as mentioned in #175?
