### ISSUE TITLE
Allow conversion of annotations to events (required for BrainVision)

### ISSUE THREAD

**Issue by hoechenberger** [cbrnr/mnelab#47]
<strike>In the data recorded using our BrainProducts system, there is no separate "stim channel", and I extract the events via
```python
mne.find_events(raw_data)
```
This is not possible using MNELAB, as the "Find events..." dialog insists I select a "stim channel", which doesn't make sense in my case. There should be the option to leave the stim channel blank, in which case `mne.find_events()` would be called with `stim_channel=None`.</strike>

I'm sorry, the original issue description doesn't make sense anymore with recent versions of `mne-python`. Here's an updated, corrected description:

The events of BrainVision data have to be generated from the annotations of the raw data:
```python
import mne

data = mne.io.read_raw_brainvision('eeg_recording.vhdr')
events = mne.events_from_annotations(data)
```
This work flow is currently not supported in MNELAB.

**Comment by hoechenberger** [comment]
I'm sorry, this issue description doesn't make sense anymore with recent versions of `mne-python`. In the newer versions, the events of BrainVision data have to be generated from the annotations of the raw data:
```python
import mne

data = mne.io.read_raw_brainvision('/Users/hoechenberger/Google Drive/TaLa/EEG_Analysis_outdated/1_DataEEG/Sub_721_071217/TaLa_721_01.vhdr')
events = mne.events_from_annotations(data)
```
This work flow is currently not supported in MNELAB.

**Comment by cbrnr** [comment]
Yeah, we need to add events from annotations.
