### ISSUE TITLE
MNELAB crashes if open file is deleted

### ISSUE THREAD

**Issue by cbrnr** [cbrnr/mnelab#65]
If a file that has been opened with MNELAB (i.e. it shows up in the list on the left side) is deleted from disk, MNELAB crashes. This also happens if e.g. I open files A, B, and C, then activate file A in the list, delete file B from disk, and then switch to file B in the list.

**Comment by stralu** [comment]
I tried to reproduce this issue for the current MNELAB version on Ubuntu 18.04 and MNELAB didn't crash. @cbrnr is the bug still the same on your system?

**Comment by cbrnr** [comment]
Interesting. You're right, it doesn't crash anymore. No idea what's changed, but I'm happy to close this issue 😄.
