### ISSUE TITLE
RuntimeError('context has already been set') 

### ISSUE THREAD

**Issue by danieltomasz** [cbrnr/mnelab#96]
after installing 0.5.1 on Ubuntu  I got following error:
```
Traceback (most recent call last):
  File "/home/daniel/.local/bin/mnelab", line 8, in <module>
    sys.exit(main())
  File "/home/daniel/.local/lib/python3.6/site-packages/mnelab/__main__.py", line 27, in main
    mp.set_start_method("spawn")  # required for Linux/macOS
  File "/usr/lib/python3.6/multiprocessing/context.py", line 242, in set_start_method
    raise RuntimeError('context has already been set')
RuntimeError: context has already been set
```

**Comment by danieltomasz** [comment]
maybe this is a possible workaround https://github.com/pytorch/pytorch/issues/3492 ?

**Comment by cbrnr** [comment]
Did 0.4.0 work OK on your machine? Can you try if moving the line `mp.set_start_method("spawn")` to the top within `main` (so right before `app_name = "MNELAB"`) solves the issue?

**Comment by danieltomasz** [comment]
I event try 0.2.0, it worked before but now doesn't; Moving the code also doesnt help; 
For this moment I  simply
```
try:
    mp.set_start_method('spawn')
except RuntimeError:
    pass
```
so I am able to run Mnelab

**Comment by cbrnr** [comment]
> I even try 0.2.0, it worked before but now doesn't

So do you mean some Ubuntu update broke this? Or a Python (package) update?

If you now run e.g. MNELAB 0.4.0 it doesn't work?

It would be interesting to understand the cause of this issue - does anything else already set the start method? Does this fix have any negative side effects?

**Comment by danieltomasz** [comment]
Running this twice on my computer (Python 3.6.8, Ipython 7.8.0) 
```
#!/usr/bin/env python3
# -*- coding: utf-8 -*-

import multiprocessing as mp
mp.set_start_method('spawn')

```
 throw the same error

```
runfile('/home/daniel/PhD/notebooks/untitled1.py', wdir='/home/daniel/PhD/notebooks')
Traceback (most recent call last):

  File "/home/daniel/PhD/notebooks/untitled1.py", line 5, in <module>
    mp.set_start_method('spawn')

  File "/usr/lib/python3.6/multiprocessing/context.py", line 242, in set_start_method
    raise RuntimeError('context has already been set')

RuntimeError: context has already been set
```

**Comment by cbrnr** [comment]
Yeah, it is a bit strange that it gets called twice, because it is protected by the `if __name__ == "__main__"` condition. How do you start MNELAB? Do you use the `mnelab` command or `python3 -m mnelab`?

It's good to know that `force=True` solves the problem, but I'd like to explore any negative side effects before integrating that into the code.

**Comment by cbrnr** [comment]
And I also wonder if this is an Ubuntu issue, because it works on my Arch Linux box. @larsoner I think you are also using Ubuntu, do you have time to quickly `pip install -U mnelab` and see if you can start it without the error?

**Comment by larsoner** [comment]
I am on Ubuntu 19.10, but with built-in Python 3.8. It starts up for me, though there are these warnings:
```
/home/larsoner/.local/lib/python3.8/site-packages/mnelab/mainwindow.py:296: DeprecationWarning: an integer is required (got type float).  Implicit conversion to integers using __int__ is deprecated, and may be removed in a future version of Python.
  splitter.setSizes((width * 0.3, width * 0.7))
/home/larsoner/.local/lib/python3.8/site-packages/mnelab/mainwindow.py:296: DeprecationWarning: an integer is required (got type float).  Implicit conversion to integers using __int__ is deprecated, and may be removed in a future version of Python.
  splitter.setSizes((width * 0.3, width * 0.7))
```
and it did not work on latest `master`, I had to switch to `maint/0.19`

**Comment by cbrnr** [comment]
Thanks @larsoner - I'll fix these issues, haven't encountered them myself because I'm not yet on 3.8.

What kind of error did you get with `master`? Does it work with the 0.19 release?

**Comment by larsoner** [comment]
Yes it opened on `maint/0.19`. On `master` there is an error because `read_montage` no longer exists

**Comment by cbrnr** [comment]
Thanks, will fix that too. I'm not sure what to do with the spawning issue though, seems like this is specific to @danieltomasz's setup. I don't understand how `main` (which includes the spawning) is called twice. The pragmatic approach would be to just include the `force` argument - do you think this safe?

**Comment by cbrnr** [comment]
Also, why do you get this warning twice?

**Comment by larsoner** [comment]
(edited to remove the `force` arg I didn't mean to have in there)

**Comment by cbrnr** [comment]
I need to use the `spawn` method because otherwise Qt doesn't play nice with Python. Thanks for the `get_context` hint, I'll look into it.

**Comment by cbrnr** [comment]
@danieltomasz could you please try the following:
- Comment out the line `mp.set_start_method("spawn")` in `__main__.py`
- Insert the line `mp.set_start_method("spawn") ` in `mainwindow.py` as the first line of the `__init__` function of the `MainWindow` class (should be line 90).

Please let me know if that works for you. Make sure to test if multiprocessing works by loading a file and computing ICA (this is currently the only thing which requires multiprocessing).
